### ISSUE TITLE
Using the -w option throws an error after updates

### ISSUE THREAD

**Issue by reilg** [jaredhanson/locomotive#167]
Working on a Windows 7 box and I just updated to version 0.12.0 for node and 2.5.1 for npm.

I'm not 100% sure if it was the update that is causing the issue but it really only started throwing an error after I did it.

Here's the error.
``` javascript
$ lcm server -w
CLI ENV: development
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn supervisor ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

Can anyone shed some light on this?

**Comment by rodrigoreis22** [comment]
After updating to Mac OSx yosemite I'm also getting:

    Rodrigos-MacBook-Pro:stationfy rodrigoreis$ lcm server -w
    CLI ENV: development 

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
