### ISSUE TITLE
locomotivejs installation throws TypeError [ERR_INVALID_CALLBACK]

### ISSUE THREAD

**Issue by fschoenfeldt** [jaredhanson/locomotive#184]
**My System:**
Ubuntu 18.10 patched as of 24.02.19
**Node -v:**
v10.15.0

Hey. Im trying to get started with Locomotivejs [following this guide](http://www.locomotivejs.org/guide/get-started/). When I try to install Locomotive via `lcm create myapp`, it throws the following error:

```
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at write (/usr/lib/node_modules/locomotive/lib/cli/create.js:336:6)
    at /usr/lib/node_modules/locomotive/lib/cli/create.js:297:5
    at /usr/lib/node_modules/locomotive/lib/cli/create.js:325:11
    at /usr/lib/node_modules/locomotive/node_modules/mkdirp/index.js:38:26
    at FSReqWrap.oncomplete (fs.js:155:5)

```
Im not sure if this error is critical so I dont want to continue trying to develop the application.

What do you guys think?

**Comment by Meivyn** [comment]
Replace this
https://github.com/jaredhanson/locomotive/blob/c1af028f8adcbfefbd218b0be6a6e227c20fefa1/lib/cli/create.js#L334-L337
By this
```js
function write(path, str) {
  fs.writeFile(path, str, function(err) {
    if (err) throw err;
  });
  console.log('   \x1b[36mcreate\x1b[0m : ' + path);
}
```

**Comment by Myolisi** [comment]
@fschoenfeldt did you manage to find your way around the above issue? Have the same problem when creating a new project.

**Comment by fschoenfeldt** [comment]
No, I didn't. And I wouldn't recommend using this project as it hasn't been updated for like 3 years.

**Comment by Myolisi** [comment]
That's what I just noticed, it had a great potential though. And it looks like the project got forked by other _contributors_  accortding to [issue 177](https://github.com/jaredhanson/locomotive/issues/177) check -> [maglev](https://github.com/viadeo/maglev) and [emvc](https://github.com/emvc/emvc)

**Comment by dragonbike** [comment]
Replace line 335 or 336 with `fs.writeFile(path, str, (err) => {});` in the file " \locomotive\lib\cli\create.js "
